service: tracking-api

plugins:
  - serverless-python-requirements
  # - serverless-domain-manager
  - serverless-stage-manager

custom:
  pythonRequirements:
    dockerizePip: non-linux
  # customDomain:
  #   domainName: ${self:custom.DOMAIN.${self:provider.stage}}
  #   certificateName: '*.listenpricing.com'
  #   basePath: ''
  #   stage: ${self:provider.stage}
  #   createRoute53Record: true
  stages:
    - dev
    - stage
    - prod
  stage: ${opt:stage, self:provider.stage}
  environment: ${file(env.yml):${self:custom.stage}, file(env.yml):dev}
  # DOMAIN:
  #   dev: api-${self:provider.stage}.listenpricing.com
  #   stage: api-${self:provider.stage}.listenpricing.com
  #   prod: api.listenpricing.com

package:
  exclude:
    - .git/**
    - node_modules/**
    - venv/**
    - __pycache__/**
    - requirements.txt
    - package-lock.json
    - package.json
    - README.md

provider:
  name: aws
  region: us-east-1
  runtime: python3.6
  stage: ${opt:stage,'dev'}
  environment:
    DB_NAME: ${self:custom.environment.db}
    DB_HOST: ${self:custom.environment.host}
    DB_PORT: ${self:custom.environment.port}
    DB_USER: ${self:custom.environment.user}
    DB_PASSWORD: ${self:custom.environment.password}

functions:
  createMonitoring:
    handler: src/functions/monitoring/create.create
    events:
      - http:
          path: monitoring
          method: post
          cors: false
          private: true

  monitoringList:
    handler: src/functions/monitoring/list._list
    events:
      - http:
          path: monitoring/list
          method: get
          cors: false
          private: true

  deleteMonitoring:
    handler: src/functions/monitoring/delete.delete
    events:
      - http:
          path: monitoring
          method: delete
          cors: false
          private: true

  updateMonitoring:
    handler: src/functions/monitoring/update.update
    events:
      - http:
          path: monitoring
          method: patch
          cors: false
          private: true

  getByIdMonitoring:
    handler: src/functions/monitoring/get_by_id.get_by_id
    events:
      - http:
          path: monitoring
          method: get
          cors: false
          private: true
